'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { ShieldCheck, ShieldAlert, ShieldX, Info, ListCheck, Activity, Search, Shield, Fingerprint, Lock, Network } from 'lucide-react';
import { cn } from '@/lib/utils';

interface AnalysisResultProps {
    data: {
        threat_level: string;
        attack_type: string;
        reasoning: string;
        risk_score: number;
        pattern_memory: {
            similarity: number;
            match_count: number;
            status: string;
        };
    };
    onReset: () => void;
}

export default function AnalysisResult({ data, onReset }: AnalysisResultProps) {
    const isHighRisk = data.risk_score > 0.6;
    const isMediumRisk = data.risk_score > 0.3 && data.risk_score <= 0.6;

    const statusColor = isHighRisk ? 'text-scam' : isMediumRisk ? 'text-warning' : 'text-safe';
    const statusBg = isHighRisk ? 'bg-scam/10' : isMediumRisk ? 'bg-warning/10' : 'bg-safe/10';
    const statusBorder = isHighRisk ? 'border-scam/20' : isMediumRisk ? 'border-warning/20' : 'border-safe/20';
    const StatusIcon = isHighRisk ? ShieldX : isMediumRisk ? ShieldAlert : ShieldCheck;

    return (
        <div className="max-w-4xl mx-auto px-6 py-20 relative z-20">
            <motion.div
                initial={{ opacity: 0, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                className="glass rounded-3xl overflow-hidden shadow-2xl border-white/5"
            >
                <div className="flex flex-col md:flex-row border-b border-border/50">
                    {/* Main Risk Score Panel */}
                    <div className="p-10 flex flex-col items-center justify-center border-r border-border/50 md:w-80 bg-zinc-900/20">
                        <h3 className="text-[10px] font-bold text-zinc-500 uppercase tracking-[0.2em] mb-8">Threat Probability</h3>
                        <div className="relative w-40 h-40 flex items-center justify-center">
                            <svg className="w-full h-full transform -rotate-90">
                                <circle
                                    cx="80" cy="80" r="70"
                                    fill="none" stroke="currentColor" strokeWidth="8"
                                    className="text-zinc-800"
                                />
                                <motion.circle
                                    cx="80" cy="80" r="70"
                                    fill="none" stroke="currentColor" strokeWidth="8"
                                    strokeDasharray={440}
                                    initial={{ strokeDashoffset: 440 }}
                                    animate={{ strokeDashoffset: 440 - (440 * data.risk_score) }}
                                    transition={{ duration: 1.5, ease: "easeOut" }}
                                    className={statusColor}
                                />
                            </svg>
                            <div className="absolute inset-0 flex flex-col items-center justify-center">
                                <span className="text-4xl font-bold text-white tracking-tighter">{(data.risk_score * 100).toFixed(0)}%</span>
                                <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Risk Factor</span>
                            </div>
                        </div>

                        <div className={cn("mt-8 px-4 py-2 rounded-full border flex items-center gap-2", statusBg, statusBorder)}>
                            <StatusIcon className={cn("w-4 h-4", statusColor)} />
                            <span className={cn("text-xs font-bold uppercase tracking-widest", statusColor)}>
                                {isHighRisk ? 'Scam Detected' : isMediumRisk ? 'Suspicious' : 'Safe Trace'}
                            </span>
                        </div>
                    </div>

                    {/* Analysis Details */}
                    <div className="flex-1 p-10 space-y-8">
                        <div className="flex justify-between items-start">
                            <div>
                                <h2 className="text-2xl font-bold text-white tracking-tight mb-2">Analysis Intelligence Report</h2>
                                <p className="text-zinc-500 text-sm">Automated scan results generated by Neural Core 2.0</p>
                            </div>
                            <button
                                onClick={onReset}
                                className="px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-white rounded-xl text-xs font-bold uppercase tracking-widest transition-standard"
                            >
                                New Scan
                            </button>
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                            <div className="p-4 rounded-2xl bg-zinc-900/40 border border-border/50">
                                <div className="flex items-center gap-2 mb-2">
                                    <Fingerprint className="w-3.5 h-3.5 text-primary" />
                                    <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Attack Vector</span>
                                </div>
                                <span className="text-white font-bold">{data.attack_type} Manipulation</span>
                            </div>
                            <div className="p-4 rounded-2xl bg-zinc-900/40 border border-border/50">
                                <div className="flex items-center gap-2 mb-2">
                                    <Activity className="w-3.5 h-3.5 text-primary" />
                                    <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Similarity Match</span>
                                </div>
                                <span className="text-white font-bold">{(data.pattern_memory.similarity * 100).toFixed(1)}% Campaign Sync</span>
                            </div>
                        </div>

                        <div>
                            <div className="flex items-center gap-2 mb-4">
                                <Info className="w-3.5 h-3.5 text-primary" />
                                <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">AI Intelligence Explanation</span>
                            </div>
                            <div className="p-6 rounded-2xl bg-primary/5 border border-primary/10 text-zinc-300 text-sm leading-relaxed font-medium">
                                "{data.reasoning}"
                            </div>
                        </div>
                    </div>
                </div>

                {/* Reasoning Steps Section */}
                <div className="p-8 bg-zinc-950/50">
                    <div className="flex items-center gap-2 mb-8">
                        <ListCheck className="w-4 h-4 text-zinc-500" />
                        <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest">Cognitive Processing Chain</span>
                    </div>

                    <div className="grid md:grid-cols-4 gap-6">
                        {[
                            { step: 1, label: 'Linguistic Layer', desc: 'Analyzed urgency and tone patterns', icon: Network },
                            { step: 2, label: 'Domain Reputation', desc: 'Checked registrar age and TTL', icon: Search },
                            { step: 3, label: 'Vector Profiling', desc: 'Identified redirection schemes', icon: Shield },
                            { step: 4, label: 'Final Verdict', desc: 'Classification based on clusters', icon: Lock },
                        ].map((node, i) => (
                            <div key={i} className="relative group">
                                <div className="flex items-center gap-3 mb-2">
                                    <div className="w-8 h-8 rounded-lg bg-zinc-900 border border-border/50 flex items-center justify-center text-xs font-bold text-zinc-500 group-hover:text-primary transition-standard">
                                        <node.icon className="w-3.5 h-3.5" />
                                    </div>
                                    <span className="text-xs font-bold text-white">Step {node.step}</span>
                                </div>
                                <h4 className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest mb-1">{node.label}</h4>
                                <p className="text-[11px] text-zinc-600 font-medium leading-[1.4]">{node.desc}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </motion.div>
        </div>
    );
}
